### ISSUE TITLE
Wrong License

### ISSUE THREAD

**Issue by splitbrain** [syntaxseed/greensteel-template#1]
With the template based on the original dokuwiki template and (as all templates do) directly using DokuWiki code, you have to be compatible with the original license which is GPL Version 2. While you can use MIT code in GPL software you can't use GPL code in MIT software. So your template has to be released under the GPL.

**Comment by syntaxseed** [comment]
Thanks Andreas. That was a hold-over from the readme that I copy-paste as a starting point. Fixed. And I will check my other plugins as well. :)
