### ISSUE TITLE
tpl_action() functions deprecated in newer dokuwiki releases.

### ISSUE THREAD

**Issue by yinxs** [syntaxseed/greensteel-template#2]
Hi, ever since the jackrum release I've been getting deprecated errors. I have to turn of the deprecated logging because they become huge. The latest release of greensteel hasn't fixed the issue it appears. I'm getting these kinds of errors:

> 2024-11-05 14:19:15		tpl_actiondropdown() is deprecated. It was called from include() in /data/web/irma/lib/tpl/greensteel/tpl_header.php:63 see devel:menus should be used instead!
> 2024-11-05 14:19:15		tpl_action() is deprecated. It was called from include() in /data/web/irma/lib/tpl/greensteel/tpl_header.php:67 see devel:menus should be used instead!

It's still working right now, but I'm expecting it to stop working in any future release now.

Hope you can take a look at it.

Kind regard, Robin

**Comment by syntaxseed** [comment]
Hi Robin,
Thank you for reporting this. I've fixed the issues, it involved a bit of a re-write of how the menus are generated in the theme - so there are slight design differences. But this should fix the warnings in the logs.

**Comment by syntaxseed** [comment]
Closing.

**Comment by syntaxseed** [comment]
Closing.

**Comment by yinxs** [comment]
That's really fast. The warnings have completely disappeared here now. Thanks!

**Comment by syntaxseed** [comment]
> That's really fast. The warnings have completely disappeared here now. Thanks!

Glad to hear it!!

If you appreciate my OSS plugins, themes, etc, there is a small donate option on my profile page. https://github.com/syntaxseed  :)
